### ISSUE TITLE
Table with SNOTEL and SNOW COURSE sites

### ISSUE THREAD

**Issue by lbross** [PSU-CSAR/bagis-pro#14] opened 2021-06-23 20:13 UTC
Separate page in the report behind the title page. Fields to include: station name, elevation, station triplet, begin date

**Comment by lbross** [comment] 2021-06-24 17:48
We may want to consider including lat and long in this table. Although the symbols for the sites appear on the maps to show the location, there is nothing to tie each symbol to its site information. By including the lat/long, it could help the analyst determine which site is which by relative position. What do you think?

**Comment by jdduh** [comment] 2021-06-24 21:50
Make sense. Please include lat and long in the site table.

**Comment by lbross** [comment] 2021-07-16 20:48
I added this a second page behind the title page for the watershed and site analysis reports. I just posted a sample for Elwha to the NWCC portal. I noticed a problem where the roads layer is duplicated and am working on that. But you can review the sites table.

**Comment by jdduh** [comment] 2021-07-16 21:08
NWCC has provided additional feedbacks on the Basin Analysis Report. I will create new issues for these updates. Here is the one related to the stations table.

**Comment by lbross** [comment] 2021-07-19 21:27
Is it OK to use the slope and aspect zones layers with the extract values to points tool? I can then look up the zone number against the definition of the slope or aspect classes to get the common name. Examples: Flat, N, NE, E ...

Also, this tool is not the speediest. Is it OK if I run the tool after clipping the sites layer and calculating the aspect or slope zones? This way I would just have to look up the value when the report is generated. Would it be helpful to save this value on the snotel or snow course sites layers like we do the name and elevation? Otherwise I might store it in the analysis.xml.

**Comment by lbross** [comment] 2021-07-20 18:56
Use 'Extract Multivalues to points' or 'Extract Values to Table' or  instead. Allow multiple input rasters. Multivalues tool will add the values to the Feature Class. Save aspect raw number and description (Flat, N, NE, E ...). Save raw value of slope, not category. These values will be saved in the analysis.xml file.

**Comment by lbross** [comment] 2021-07-30 21:16
Ugh!! I thought I had this working but it fails on CS3. I am getting an error with the Extract Values to Table gp tool. It won't run interactively either. When I add the third raster layer in the UI it gives me an error about that layer not having the same spatial reference. But I looked at all the layers and the spatial reference looks fine. I wonder if this is a bug with the new version of Pro? CS3 is running 2.8.1 and my laptop is running 2.6.3.

Can you see if you can run the tool both on your laptop and on CS3? Either of the sites layers is the feature layer and I am extracting from aspect, slope, and aspzone. Thanks!

**Comment by jdduh** [comment] 2021-07-30 22:31
I got the same error message in Pro 2.8.1 with our AOI data. I then used the AOI dem to create slope and aspect layers. These outputs seem to work fine. I believe that the rasters in a BAGIS AOI don't have the same extent due to that we used different buffers to perform different analyses. After viewing the output table of the Extract Values to Table tool, I start to think that this might not be an easier tool to use than the Extract Values to Point tool. Attached below is a screenshot of the output table. There were two input point features and three input rasters. The output table has 6 (i.e., 2 x 3) records. You cannot join the table to the point featureclass to get what we want. We probably should use the Extract Values to Point tool.

![ExtractValuesToTable_Output](https://user-images.githubusercontent.com/11510708/127717770-1a852775-8266-4e75-9550-a4b41f8e3c91.png)

**Comment by jdduh** [comment] 2021-08-02 07:02
Please use the Extract Multi Values to Points tool. If you don't feel like to alter the input station featureclasses, then you can make a copy of the input featureclasses and use them to extract raster values.

**Comment by lbross** [comment] 2021-08-03 23:27
I had the Extract Values to Table gp tool working well even with that unusual table structure, but if it is unreliable with different extents then it is best not to use it. From a productivity perspective, this means that the work I did last week is wasted, but that's how it goes sometimes.
Your mention of the Extract Multi Values to Points tool reminded me that we use this tool for the elevation precipitation correlation chart to extract the precipitation and aspect direction for the sites. This function creates a single feature class with both snotel and snow course sites and appends the precipitation and aspect direction to the feature class. We can add the slope and aspect degrees to this feature class and use it for both elevation precip and the sites information on the report. This means we could add the precipitation value to the report if we want. The elevation precipitation correlation chart takes a long time to generate and this approach would distribute the processing time through some other functions. Also the old code for the sites table on the report did everything twice for snotel and snow course. It would only have one feature class with this new design. Here is a rough outline:
1. When sites layers are clipped, create a combined sites table called merged_sites
2. Add fields for BA_PRECIP, BA_ASPECT, BA_DIRECT, BA_SLOPE
3. Extract Values to points for precipitation, aspect, and slope to populate these fields
4. Use add Join tool for each extract layer
5. Use Calculate Field gp tool to update merged_sites
6. Use Remove join tool after merged_sites is updated
7. If aspzones exists, extract aspect direction when sites are clipped; Recalculate this when generating aspect layer
8. Recalculate and update BA_precip when precip sites clipped
9. Update Elevation Precipitation algorithm to use merged_sites instead of prec_stel with edits to ensure that BA_PRECIP and BA_DIRECT are populated

**Comment by jdduh** [comment] 2021-08-03 23:39
Sounds good. Make sure that the table in the report has clear/descriptive headings. If there is a design limitation, then we can add a text box on the report page displaying the detail column descriptions and data units.

**Comment by lbross** [comment] 2021-08-04 16:59
This is my most recent iteration. The updated version will look the same but the data will be generated differently. Let me know if you have any changes or want me to add PRISM data.
[sites_table_8.pdf](https://github.com/PSU-CSAR/bagis-pro/files/6933077/sites_table_8.pdf)

**Comment by lbross** [comment] 2021-08-16 18:24
Again, I thought I was almost done with this, but it is not working the same on Pro 2.8.1 on CS3. I am using the Data Management Merge tool to merge the Snotel and Snow Course layers into a single layer with all sites. When I run in on 2.6.3 it is fine, but on 2.8.1 it doesn't copy any of the attributes for the second layer (snow course) to the new feature class. My guess is that it is in the field mapping, but I'm not sure where the problem is. I don't want to merge any attributes between the two classes, just to combine all the records. It works on 2.6.3 without any specified field mapping. Any thoughts or maybe a different tool I could use for this purpose?

**Comment by jdduh** [comment] 2021-08-16 20:52
I believe this is a bug in 2.8.1. The only way to "fix" it for now is to set a value in the mergeRule attribute explicitly. It doesn't matter what value you set to which attribute field. Once the code "touches" the merge tool's parameters, the tool seems to work correctly.

**Comment by jdduh** [comment] 2021-08-16 20:58
The pdf example looks good. Please change the "Descr" heading text to "Aspect Descr".

**Comment by lbross** [comment] 2021-08-16 21:30
Thanks for the info about the bug :-( I just got it working with the Append tool so will leave that in place for now. I will update the Descr column.

**Comment by lbross** [comment] 2021-08-16 22:33
Another quirky problem with 2.8.1. This time with the sample tool. When I try to run it with these parameters on CS3, I get an  ERROR 010555: Internal error in Sample: %s.

Input rasters
D:\AOIs\2020_NWCC_Basin_Analysis_AOIs\UCO\Yampa\elk_r_nr_milner_09032010\analysis.gdb\aspzoneprec;
D:\AOIs\2020_NWCC_Basin_Analysis_AOIs\UCO\Yampa\elk_r_nr_milner_09032010\prism.gdb\Annual;
D:\AOIs\2020_NWCC_Basin_Analysis_AOIs\UCO\Yampa\elk_r_nr_milner_09032010\analysis.gdb\precmeanelev

Input location raster
D:\AOIs\2020_NWCC_Basin_Analysis_AOIs\UCO\Yampa\elk_r_nr_milner_09032010\prism.gdb\Annual

Output table
D:\AOIs\2020_NWCC_Basin_Analysis_AOIs\UCO\Yampa\elk_r_nr_milner_09032010\analysis.gdb\precmeanelev_tbl

"NEAREST"

It looks like the extents are slightly different for a couple of the rasters but this is also the case in another sample AOI and the tool runs fine. I don't think I'm a fan of 2.8.1. It looks like there is a new version. Should I upgrade CS3?

**Comment by jdduh** [comment] 2021-08-16 23:00
It needs admin privilege to upgrade. I will perform the upgrade later today. Let me try the sample tool on my 2.8.1 and later on 2.8.2.

**Comment by jdduh** [comment] 2021-08-16 23:13
I was able to run the sample tool without any problem on 2.8.1. Did you set the unique ID field value?

Sample
=====================
Parameters

Input rasters     C:\NWCC\AOIs\Little_Wood_R_ab_High_Five_Ck_AOI\analysis.gdb\aspzoneprec;C:\NWCC\AOIs\Little_Wood_R_ab_High_Five_Ck_AOI\analysis.gdb\precmeanelev;C:\NWCC\AOIs\Little_Wood_R_ab_High_Five_Ck_AOI\prism.gdb\Annual
Input location raster or features     C:\NWCC\AOIs\Little_Wood_R_ab_High_Five_Ck_AOI\prism.gdb\Annual
Output table or feature class     C:\workspace\workspace default.gdb\sample_output2
Resampling technique     NEAREST
Unique ID field     VALUE
Process as multidimensional     CURRENT_SLICE
Acquisition information of location data     
Statistics type     
Percentile value     
Buffer distance field or value     
Column-wise layout     ROW_WISE
Generate feature class     TABLE
=====================
Messages

Start Time: Monday, August 16, 2021 4:07:27 PM
Spatial reference wkid and wkt for sample table sample_output2 are [0, PROJCS["NAD_1983_Albers",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Albers"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["central_meridian",-96.0],PARAMETER["Standard_Parallel_1",29.5],PARAMETER["Standard_Parallel_2",45.5],PARAMETER["latitude_of_origin",23.0],UNIT["Meter",1.0]]].
Succeeded at Monday, August 16, 2021 4:07:30 PM (Elapsed Time: 2.58 seconds)

**Comment by lbross** [comment] 2021-08-17 17:40
Thanks for taking a look at this. I am perplexed. I copied the 3 layers into a new .gdb and the Sample tool ran fine. It also ran fine with a different AOI. I ran the tool interactively with the original layers and it completed successfully. I just tried running the full process again and got the internal error :-( I see that you did not update ArcGIS Pro. I can do it because I have the admin information, but I don't know if it will help. I have a couple more things to test

**Comment by jdduh** [comment] 2021-08-18 21:42
Got the same error message using your data on Pro 2.8.2. I will let you know if I figure out the problem with the gdb that you provided.

Sample
=====================
Parameters

Input rasters     C:\workspace\aoitest\sample.gdb\aspzoneprec;C:\workspace\aoitest\sample.gdb\Annual;C:\workspace\aoitest\sample.gdb\precmeanelev
Input location raster or features     C:\workspace\aoitest\sample.gdb\Annual
Output table or feature class     C:\workspace\aoitest\sample.gdb\precmeanelev_tbl2
Resampling technique     NEAREST
Unique ID field     VALUE
Process as multidimensional     CURRENT_SLICE
Acquisition information of location data     
Statistics type     
Percentile value     
Buffer distance field or value     
Column-wise layout     ROW_WISE
Generate feature class     TABLE
=====================
Messages

Start Time: Wednesday, August 18, 2021 2:40:18 PM
ERROR 010555: Internal error in Sample: %s.
Failed to execute (Sample).
Failed at Wednesday, August 18, 2021 2:40:20 PM (Elapsed Time: 2.16 seconds)

**Comment by lbross** [comment] 2021-08-18 22:02
I feel better. At least now we have a sample we can provide to ESRI

**Comment by jdduh** [comment] 2021-09-14 23:18
Per the sample tool, ESRI has confirmed that it's a bug. The temporary workaround is to activate the "Create Feature Class" option when executing the tool. That seems to solve the problem.

**Comment by lbross** [comment] 2021-09-16 21:48
Switched to the feature class option. Updated code that generates the precipitation correlation feature class and that creates the chart from the feature class. Confirmed that the fixed worked for the elk_r_nr_milner aoi. Uploaded new watershed report to the portal

**Comment by jdduh** [comment] 2021-09-24 06:36
The table and maps look good. Some of the station numbers on the maps are obscured. Please force the placement of all labels. See this page for more information: https://pro.arcgis.com/en/pro-app/2.7/help/mapping/text/force-the-placement-of-all-labels-in-a-label-class.htm

![image](https://user-images.githubusercontent.com/11510708/134629252-8482e931-04a0-467c-9848-643394bf2a09.png)

**Comment by lbross** [comment] 2021-10-06 22:45
I tried your second approach and it seems to work well. Merging the sites into a single file would require much more rework. Please let me know what you think of the new sample.
[label_test.pdf](https://github.com/PSU-CSAR/bagis-pro/files/7297531/label_test.pdf)

**Comment by jdduh** [comment] 2021-10-06 23:01
How about placing the labels in similar (as oppose to opposite) directions? Upper left and upper right or lower left and lower right? I know this doesn't solve all possible placement conflicts but let's give it a try when we test the batch tool on multiple AOIs.

**Comment by lbross** [comment] 2021-11-29 22:29
1. Update batch tool settings. Set SnotelBufferDistance to 5 and SnotelBufferUnits to Kilometers
2. Rename “Id” column to “Site #” in table

**Comment by lbross** [comment] 2021-12-13 22:01
1. @jdduh to email Gus
2. Use batch tool buffer settings for both sites and PRISM buffer layer
3. No questions
4. 'SNOTEL Rep Area' and 'Snow Courses Rep Area'

**Comment by jdduh** [comment] 2021-12-14 18:01
Per item#1, we could clip a separate copy of the DEM to the AOI with the required buffer distance (5 km) and calculate SLOPE on it. These additional "surface" layers will be saved to AOI's report layer folder/GDB. The original DEM and SLOPE won't be altered.

**Comment by lbross** [comment] 2021-12-14 23:01
We would need to do ASPECT too. Do we need to do any processing after clipping the DEM to make it a "filled" DEM? We do all of our analysis on the filled DEM. I'm not sure how this is will work with the charts, especially the Precipitation Correlation chart. But I guess we can try.

**Comment by jdduh** [comment] 2021-12-14 23:11
Yes, we need ASPECT. There is no need to fill the DEM. We shouldn't perform the analysis on the filled DEM, but I think the difference of the results is negligible. Filled DEM is not the real DEM and should only be used for watershed delineation purpose.

We can limit the precipitation correlation calculation to the extent of the PRISM raster. Have we set the extent explicitly in these analyses?

**Comment by lbross** [comment] 2022-01-03 23:15
Just finished extracting the PRISM values for the sites outside the PRISM buffer. It seems to flow pretty good and they are included in the elevation precipitation calculation. At this point it would be more work to exclude them, but I can look into that if we need to.

**Comment by jdduh** [comment] 2022-04-14 21:38
Truckee R at Farad 10346000:CA:USGS has too many sites to fit on one page. I believe we will encounter more of these when generating reports for large AOIs. This AOI has a total of 46 sites/stations. The site table can only fit 35 sites on one page. We need to create an appendix if an AOI has more than 35 sites and leave the site page blank (with the text directing the readers to the appendix). The appendix will be added to the end of the report.

**Comment by jdduh** [comment] 2022-04-14 21:46
This is text for the active sites table page when there are more than 35 sites in the AOI.

"ACTIVE SITES TABLE
This watershed has more than 35 sites. See Appendix for the complete list of sites.
THIS PAGE INTENTIONALLY LEFT BLANK"

Do we have a similar blank page when there is no site in the AOI?

**Comment by lbross** [comment] 2022-04-19 20:40
This is done. I overwrote a sample report on the FTP server called 10217000_UT_USGS_Watershed-Report.pdf for your review. I dropped the maximum number of sites to 25 because sometimes the names of the sites wrap, so that a table with 35 sites is still too long for 1 page. The page break is not always where we might want it to be, but because this is html I can't control that.
We did not have a similar blank page when there are no sites in the AOI. We do now :-)

**Comment by jdduh** [comment] 2022-04-19 21:13
Looks good. This particular report doesn't have maps on the multiple-map pages. Just want to make sure that's because you turned the option off for debugging purpose.

**Comment by lbross** [comment] 2022-04-19 21:20
You are correct. The multiple-map pages were disabled for debugging. Glad it looks good.

**Comment by jdduh** [comment] 2022-09-22 19:15
Obscured station number (see the image below). I believe that we talked about this issue but NWCC brought it up again. This could be a design challenge. Do you have any thought? We could expand the map frame to cover a larger area, but all the maps will look smaller.

![image](https://user-images.githubusercontent.com/11510708/191832179-bfd3bf9e-1984-46a5-a751-ac40ac7826a0.png)

**Comment by lbross** [comment] 2022-09-22 22:34
We inherited the MapFrame dimensions from BAGIS V3. We set the upper right and lower left corners when we create the map frame. The current values are:
LL 1.0, 3.0
UR 7.5, 10.0

It looks like we may have some space to give horizontally, but not vertically due to the other map elements.

The envelope for the map comes from extent of the unbuffered AOI vector. There is a configurable expansion factor that can be set. It is currently set to 1.1 but could be changed.

Let me know what you think.

**Comment by jdduh** [comment] 2022-09-23 01:21
We could make the MapFrame a little bigger (e.g., 0.7, 2.7 for LL and 7.8, 10.3 for UR) and set the expansion factor to, say, 1.3. This also assumes that the background of the MapFrame is transparent and won't obscure other map elements. Please give it a try and see how the map looks (and if it shows all the station numbers for the San Miguel River AOI). We might need to tweak the frame size and expansion factor.

**Comment by lbross** [comment] 2022-09-23 21:03
Just a quick update. I've spent most of my time today on this and am puzzled. When I change any of the dimensions for the envelope, even just 0.5 inch, the maps no longer load in the center of the map frame. The vertical positioning seems wrong. ArcGIS must be doing some calculation with the coordinates that I can't figure out. The layout size is set to 8.5 x 11 because we are doing letter page size. And when I look at the layout dimensions in the Pro Client, the numbers that are reported don't reflect the xMin xMax etc. I will keep plugging away next week, but wanted to see if you had any ideas?

**Comment by jdduh** [comment] 2022-09-29 19:10
A new request related to the table - please list all the stations (SNOTEL and Snow Course) according to their elevations, from low to high. The stations are numbered in this order.

Per the previous layout question, please check the tool arguments. Make sure they are taking LL and UR page coordinates, instead of LL, X-size, and Y-size values. I believe ESRI SDK might have made that change when we moved from VBA to .NET.

**Comment by lbross** [comment] 2022-09-29 22:00
Can I get some clarification on the new request? Assume the SNOTEL and Snow Course sites should be intermingled depending on their elevation. Also you say "the stations are numbered in this order". I'm looking at the merged_sites layer which is the source of this table and this is not the case. Do you mean the stations should be numbered in this order?

**Comment by jdduh** [comment] 2022-09-30 00:13
Sort the intermingled stations in the merged_sites layer on Elevation from low to high (ascendingly). Number the stations from 1 from the top of the list (i.e., from the lowest one). We might need to read the station attributes to an array and sort the array if we cannot sort the records in the layer's attribute table.

**Comment by lbross** [comment] 2022-09-30 18:23
I tested a different way to zoom to the AOI extent. I set the Camera on the MapFrame rather than zooming on the MapView. This seems to work more reliably than the original approach. It may even help with the map layers that don't display. I am attaching a map for San Miguel with the settings you requested. Please review. Sometimes I think succeeding with ArcGIS development is 60% dumb luck :-)

**Comment by jdduh** [comment] 2022-09-30 18:50
Looks good. The new map looks like having a smaller scale then the original map. Can you make the MapFrame a little bigger  (e.g., 0.5, 2.5 for LL and 8.0, 10.5 for UR)? We have to test the new layout on other AOIs that have different size and shape. Dumb luck? I think that's more like expert intuition.

**Comment by jdduh** [comment] 2022-11-02 21:34
New spec for the station table and related maps/analysis. We need to add the following two AWDB active stations to the AOI.
- Snolite (SNTLT): http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_SNTLT_ACTIVE/FeatureServer
- Cooperator Snow Pillows (MSNT): http://webservices.geog.pdx.edu/arcgis/rest/services/AWDB_ACTIVE/stations_MSNT_ACTIVE/FeatureServer

Adding the two new layers involves the following tasks:
1. Clip them to the AOI and store them with the existing SNOTEL and Snow Course layers
2. Include them in the Site Representation analysis, combining the two new layers with SNOTEL, and label the analysis as "Automated Sites" throughout the report. The Snow Course site maps/analysis remain unchanged.
3. Add the two layers to all the maps. They need to have different map symbols from the SNOTEL and Snow Course sites.
4. The Type column in the active site table should include the correct site types for the new sites, that is, Snolite and Snow Pillows (I will confirm the preferred names).

**Comment by lbross** [comment] 2022-11-02 21:59
If I understand correctly we want to combine the 3 site layers as "Automated Sites" everywhere except for the maps and active sites table. This includes the title page (site count within and outside basin, network representation analysis), snow course sites representation map, and the site distribution charts.

Also we currently have separate batch tool configuration settings to set the buffer for snotel and snow course. Is it okay to reuse the snotel buffer settings for these new layers?

**Comment by jdduh** [comment] 2022-11-02 22:41
You are correct. Combine SNOTEL, Snolite, and MSNT into one automated site layer in analysis, including the site representation analysis on the title page.

Yes, please use the same buffer distance as SNOTEL.

**Comment by lbross** [comment] 2022-11-07 23:37
Do we have a webservice that has most of the AOI polygons? These new sites layers are not well-distributed and I'm having trouble finding test AOIs that have these sites within their boundaries. Or if you are aware of some AOIs that cover these sites, that would work too.

**Comment by jdduh** [comment] 2022-11-08 00:53
We have a webmap of the AOIs. You can add it directly from BAGIS V3's "Add Reference Layers" button, or open the BAGIS_Reference_Map.lyr file that's downloaded to user's BAGIS' system folder.

http://webservices.geog.pdx.edu/arcgis/rest/services/BAGIS_GISLayers/BAGIS_Reference_Maps/MapServer

**Comment by jdduh** [comment] 2022-11-10 22:48
Just to confirm the site names displayed in the table. The notes are for reference only.

awdb_name, display_name, notes
MSNT, Coop Pillow , Active Cooperator Snow Pillows (automated)
SNOW, Snow Course, Active NRCS snow course sites
SNTL, Snotel, Active NWCC SNOTEL (for SNOw TELemetry) sites (automated)
SNTLT,  Snolite, Active NWCC SNOTEL Lite sites (automated)

**Comment by lbross** [comment] 2022-11-10 23:07
I'm not sure what to do with some of this information.
awdb_name: We don't display this anywhere other than as part of the web service name on the data sources table
display_name: Is this for the the 'Type' field on the Active Sites table? The Type is part of a C# enumeration so it can't have spaces in it but we can do CoopPillow and SnowCourse
notes: You said this is for reference only so I won't add it anywhere

I should clarify the name for the new layers on the maps: "Coop Pillow" and "Snolite"?

**Comment by jdduh** [comment] 2022-11-11 01:43
Here are the Type names to be displayed in the table.

Snotel, SnowCourse, CoopPillow, Snolite
![image](https://user-images.githubusercontent.com/11510708/201243409-d8d97bf0-67fe-4657-83b7-25fcaa22710e.png)

The layer names on the map legend:
Coop Pillow
Snolite
Snotel (delete "sites")
Snow Course (delete "s")

![image](https://user-images.githubusercontent.com/11510708/201243749-0d6baae8-b83f-469d-9f46-572e82219ccc.png)

**Comment by lbross** [comment] 2022-11-14 21:36
Pro is not letting me merge the Snolite sites with the snotel and snow course sites. It says the schema is different. I don't see anything obvious and these feature classes have over 40 fields. Is there a tool that can compare attribute tables across feature classes?

**Comment by jdduh** [comment] 2022-11-16 18:50
The AWDB webservices of all the station types (except for the USGS_ACTIVE service) have the same attribute fields (see the complete list below). I believe the batch tool added some additional fields into the SNTL and SNOW layers for reporting use. These fields need to be added to the MSNT and SNTLT layers as well.

These seem to be the additional fields in SNTL and SNOW layers in the AOIs.
BA_SNAME text
BA_SELEV double
BA_STYPE text
BA_SITE_ID long

SNTL
Fields:
objectid ( type: esriFieldTypeOID , alias: objectid , editable: false , nullable: false )
actonid ( type: esriFieldTypeString , alias: actonid , editable: true , nullable: true , length: 20 )
begindate ( type: esriFieldTypeDate , alias: begindate , editable: true , nullable: true , length: 8 )
countyname ( type: esriFieldTypeString , alias: countyname , editable: true , nullable: true , length: 25 )
enddate ( type: esriFieldTypeDate , alias: enddate , editable: true , nullable: true , length: 8 )
fipscountrycd ( type: esriFieldTypeString , alias: fipscountrycd , editable: true , nullable: true , length: 5 )
fipscountycd ( type: esriFieldTypeSmallInteger , alias: fipscountycd , editable: true , nullable: true )
fipsstatenumber ( type: esriFieldTypeSmallInteger , alias: fipsstatenumber , editable: true , nullable: true )
huc ( type: esriFieldTypeString , alias: huc , editable: true , nullable: true , length: 20 )
name ( type: esriFieldTypeString , alias: name , editable: true , nullable: true , length: 100 )
shefid ( type: esriFieldTypeString , alias: shefid , editable: true , nullable: true , length: 20 )
stationdatatimezone ( type: esriFieldTypeDouble , alias: stationdatatimezone , editable: true , nullable: true )
stationtimezone ( type: esriFieldTypeDouble , alias: stationtimezone , editable: true , nullable: true )
stationtriplet ( type: esriFieldTypeString , alias: stationtriplet , editable: true , nullable: true , length: 50 )
elevation ( type: esriFieldTypeDouble , alias: elevation , editable: true , nullable: true )
latitude ( type: esriFieldTypeDouble , alias: latitude , editable: true , nullable: true )
longitude ( type: esriFieldTypeDouble , alias: longitude , editable: true , nullable: true )

SNTLT
Fields:
objectid ( type: esriFieldTypeOID , alias: objectid , editable: false , nullable: false )
actonid ( type: esriFieldTypeString , alias: actonid , editable: true , nullable: true , length: 20 )
begindate ( type: esriFieldTypeDate , alias: begindate , editable: true , nullable: true , length: 8 )
countyname ( type: esriFieldTypeString , alias: countyname , editable: true , nullable: true , length: 25 )
enddate ( type: esriFieldTypeDate , alias: enddate , editable: true , nullable: true , length: 8 )
fipscountrycd ( type: esriFieldTypeString , alias: fipscountrycd , editable: true , nullable: true , length: 5 )
fipscountycd ( type: esriFieldTypeSmallInteger , alias: fipscountycd , editable: true , nullable: true )
fipsstatenumber ( type: esriFieldTypeSmallInteger , alias: fipsstatenumber , editable: true , nullable: true )
huc ( type: esriFieldTypeString , alias: huc , editable: true , nullable: true , length: 20 )
name ( type: esriFieldTypeString , alias: name , editable: true , nullable: true , length: 100 )
shefid ( type: esriFieldTypeString , alias: shefid , editable: true , nullable: true , length: 20 )
stationdatatimezone ( type: esriFieldTypeDouble , alias: stationdatatimezone , editable: true , nullable: true )
stationtimezone ( type: esriFieldTypeDouble , alias: stationtimezone , editable: true , nullable: true )
stationtriplet ( type: esriFieldTypeString , alias: stationtriplet , editable: true , nullable: true , length: 50 )
elevation ( type: esriFieldTypeDouble , alias: elevation , editable: true , nullable: true )
latitude ( type: esriFieldTypeDouble , alias: latitude , editable: true , nullable: true )
longitude ( type: esriFieldTypeDouble , alias: longitude , editable: true , nullable: true )

SNOW
Fields:
objectid ( type: esriFieldTypeOID , alias: objectid , editable: false , nullable: false )
actonid ( type: esriFieldTypeString , alias: actonid , editable: true , nullable: true , length: 20 )
begindate ( type: esriFieldTypeDate , alias: begindate , editable: true , nullable: true , length: 8 )
countyname ( type: esriFieldTypeString , alias: countyname , editable: true , nullable: true , length: 25 )
enddate ( type: esriFieldTypeDate , alias: enddate , editable: true , nullable: true , length: 8 )
fipscountrycd ( type: esriFieldTypeString , alias: fipscountrycd , editable: true , nullable: true , length: 5 )
fipscountycd ( type: esriFieldTypeSmallInteger , alias: fipscountycd , editable: true , nullable: true )
fipsstatenumber ( type: esriFieldTypeSmallInteger , alias: fipsstatenumber , editable: true , nullable: true )
huc ( type: esriFieldTypeString , alias: huc , editable: true , nullable: true , length: 20 )
name ( type: esriFieldTypeString , alias: name , editable: true , nullable: true , length: 100 )
shefid ( type: esriFieldTypeString , alias: shefid , editable: true , nullable: true , length: 20 )
stationdatatimezone ( type: esriFieldTypeDouble , alias: stationdatatimezone , editable: true , nullable: true )
stationtimezone ( type: esriFieldTypeDouble , alias: stationtimezone , editable: true , nullable: true )
stationtriplet ( type: esriFieldTypeString , alias: stationtriplet , editable: true , nullable: true , length: 50 )
elevation ( type: esriFieldTypeDouble , alias: elevation , editable: true , nullable: true )
latitude ( type: esriFieldTypeDouble , alias: latitude , editable: true , nullable: true )
longitude ( type: esriFieldTypeDouble , alias: longitude , editable: true , nullable: true )

MSNT
Fields:
objectid ( type: esriFieldTypeOID , alias: objectid , editable: false , nullable: false )
actonid ( type: esriFieldTypeString , alias: actonid , editable: true , nullable: true , length: 20 )
begindate ( type: esriFieldTypeDate , alias: begindate , editable: true , nullable: true , length: 8 )
countyname ( type: esriFieldTypeString , alias: countyname , editable: true , nullable: true , length: 25 )
enddate ( type: esriFieldTypeDate , alias: enddate , editable: true , nullable: true , length: 8 )
fipscountrycd ( type: esriFieldTypeString , alias: fipscountrycd , editable: true , nullable: true , length: 5 )
fipscountycd ( type: esriFieldTypeSmallInteger , alias: fipscountycd , editable: true , nullable: true )
fipsstatenumber ( type: esriFieldTypeSmallInteger , alias: fipsstatenumber , editable: true , nullable: true )
huc ( type: esriFieldTypeString , alias: huc , editable: true , nullable: true , length: 20 )
name ( type: esriFieldTypeString , alias: name , editable: true , nullable: true , length: 100 )
shefid ( type: esriFieldTypeString , alias: shefid , editable: true , nullable: true , length: 20 )
stationdatatimezone ( type: esriFieldTypeDouble , alias: stationdatatimezone , editable: true , nullable: true )
stationtimezone ( type: esriFieldTypeDouble , alias: stationtimezone , editable: true , nullable: true )
stationtriplet ( type: esriFieldTypeString , alias: stationtriplet , editable: true , nullable: true , length: 50 )
elevation ( type: esriFieldTypeDouble , alias: elevation , editable: true , nullable: true )
latitude ( type: esriFieldTypeDouble , alias: latitude , editable: true , nullable: true )
longitude ( type: esriFieldTypeDouble , alias: longitude , editable: true , nullable: true )

**Comment by jdduh** [comment] 2022-11-16 18:52
Thanks for the update.

**Comment by lbross** [comment] 2022-11-21 22:05
A couple of notes on this:

1. The label 'Automated Sites Rep Area' is too long and causes Pro to omit this layer from the legend. I changed it to 'Auto Sites Rep Area' but am open to suggestions.
2. This change requires updates to the layout files for the multiple pane maps because we are adding sites layers. You'll want to delete any .pagx files from the BAGIS directory in your AppData folder. If they are missing, Pro will automatically download the latest from ArcGIS online.

**Comment by jdduh** [comment] 2022-12-30 21:08
Is there a way to separate the site table into multiple pages at the cell border? This is only for the reports of the AOIs with more than 25 sites. Here is a screenshot of the issue.

![image](https://user-images.githubusercontent.com/11510708/210111733-3975f181-f967-42ea-a5a7-28f00aeb2cfc.png)

**Comment by lbross** [comment] 2023-01-03 18:24
Remember that the technology behind this page uses html for formatting and html has limited options for keeping track of the page size. I may be able to do something with paginating an html table.

**Comment by lbross** [comment] 2023-01-05 00:46
Just posted a new version of the Add-In to basins that should fix this. Please test and let me know if you have any issues. It reprints the column headers and title at the top of the page, but that's not a bad thing.

**Closed** 2023-01-05 07:10 UTC

**Comment by jdduh** [comment] 2023-01-23 20:38
Just to note that when there is no site in the AOI the batch tool puts an error message in the logfile and shows "Error" in the AOI listbox. The analysis report is still created without any other issues. Here is an example.

01/23/23 12:18:53 Completed batch PDF export WITH ERRORS for bull_lake_ck_nr_lenore_11022010. The output is located at E:\NWCC\AOI_BasinAnalysisReports_MissouriPlatte\MissouriPlatte\Bighorn\bull_lake_ck_nr_lenore_11022010\maps_publish
Check for errors in the logs at E:\NWCC\AOI_BasinAnalysisReports_MissouriPlatte\MissouriPlatte\Bighorn\bull_lake_ck_nr_lenore_11022010\logs! 

![image](https://user-images.githubusercontent.com/11510708/214144634-bc6c18bf-d3d9-4f6b-a87c-a9160eb03a4c.png)
