### ISSUE TITLE
Basin Analysis Report - Summary Page

### ISSUE THREAD

**Issue by jdduh** [PSU-CSAR/bagis-pro#21] opened 2021-08-26 21:31 UTC
SNOTEL Sites: within basin – 2, outside basin – 0 (See SNOTEL SITES REPRESENTATION map)
Snow Courses: within basin – 0, outside basin – 2 (See SNOW COURSE SITES REPRESENTATION map)

Report the buffer distance that are used to clip the SNOTEL and Snow Courses layer. Is this a customizable value for the batch process? The summary would be something like:

SNOTEL Sites: within basin – 2, **within a 5 miles buffer distance** outside basin – 0 (See SNOTEL SITES REPRESENTATION map)
Snow Courses: within basin – 0, **within a 5 miles buffer distance** outside basin – 2 (See SNOW COURSE SITES REPRESENTATION map)

**Comment by lbross** [comment] 2021-09-07 21:58
I would have bet money that the buffer distance was already on the title page. It was in the requirements but somehow initially missed. The infrastructure was there though and this is now done, along with the requested text.

**Comment by jdduh** [comment] 2021-09-24 06:46
The Arkansas R at Salida report's summary page shows that "SNOTEL Sites: within basin – 2, within a 100 Meters buffer distance outside basin – 1". Can you verify that 100 meters is the correct buffer distance? I thought the buffer distance could be longer.

**Comment by lbross** [comment] 2021-09-24 18:08
The default buffer distance for clipping the sites layers to the AOI is 100 Meters. This is easy to change if you want too. Let me know. The desired buffer distance is being passed correctly through the code and is being stored correctly in the sites metadata. HOWEVER ... the function that clips the sites starts with the buffered AOI and then adds the desired buffer on top of that which is incorrect. I will fix this in the next release. I used the measure tool and could tell that the actual buffer was longer than what BAGIS-PRO thought it was using.

**Comment by lbross** [comment] 2021-11-29 22:44
1. What do we show for buffer distance when there are no sites? Currently we print “Snow Courses: within basin – 0, within a ? buffer distance outside basin – 0”
2. The site representation definition should read "5.642 miles planar radius and 500 feet above and below site elevation”
3.  Add a new Data Sources Page immediately following Title Page. Write Data Sources here instead of on Title Page

**Comment by jdduh** [comment] 2022-04-05 18:32
See this document (https://docs.google.com/document/d/11k7kbv6pxP164z3W24vJUGsnlPoLqSJM/edit?usp=sharing&ouid=114144681831151941835&rtpof=true&sd=true) for the updates on the summary page and the data sources page. Hopefully the data sources information fits on one page.

**Comment by lbross** [comment] 2022-04-05 20:06
Can you tell me why the urls are highlighted by magenta in the data sources page? I know that Land Ownership layer url has just changed. I did that yesterday. But the roads layer looks to be the same.

**Comment by jdduh** [comment] 2022-04-05 20:09
We have a new source data service for the land ownership layer and will have a new FS roads service. These URLs need to be updated.

**Comment by lbross** [comment] 2022-04-05 21:27
I have updated the land ownership layer per your request from late last week. It sounds like there is a separate update coming for roads.

**Comment by jdduh** [comment] 2022-04-06 00:00
The new roads layer is published. https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/USFS_FSTopo_Transport_LN/FeatureServer

**Comment by lbross** [comment] 2022-04-06 22:57
I posted a new version of the 06228000_WY_USGS Watershed Report to the NWCC report. Updates include

- The changes you requested to the title page and the data sources page. The data sources still fit on one page!
- The new layers for land ownership and public lands. This AOI has some AIR land so we can prove it!
- I made the patches smaller on the elevation, land cover, and precipitation contribution layers to make the legend smaller. Should either of these be yet smaller?
Please review.

**Comment by jdduh** [comment] 2022-04-06 23:32
The legend looks good. Here are some issues that I spotted in the report.
1. Summary page: add one blank line above the Network Representation Analysis and one blank line above Potential Site Location Analysis (remove the blank line after it if there is one). Just to confirm that the road buffer distance (e.g., 300) comes from the batch parameter file.
2. On the Roads, Federal Non-Wilderness & Tribal Land map, change the legend label from "Federal Non-Wilderness Land" to "Suitable Land Ownership Type" (or anything that you think would represent "federal non-wilderness and tribal land".)

**Comment by lbross** [comment] 2022-04-07 21:42
The summary page was harder to fix that it should have been. I think there is a bug in the open source library we're using to convert html to pdf. The list seems to throw it off. I came up with a workaround. The buffer distance is actually stored in the buffered feature class and yes, we pull it from there. This way if the batch parameter file changes after the layer is created, we still have the correct distance.
I changed the label on that map.
I posted a "final" prototype to the basins FTP server in the /BAGIS/BAGIS Reports folder. If this looks good, let me know and I will get the remaining 18 map packages generated and posted.

**Comment by jdduh** [comment] 2022-11-18 23:40
descriptions for some of the data sources are listed below. This is related to the information in this file: https://ebagis.geog.pdx.edu/api/rest/desktop/settings/bagis-pro/

**New entry - please add this to the data sources page in the report. This entry also has a short description.**
        {
            "description": "Elevation Data Source - One arc-second (approximately 30 meters) USGS National Elevaton Dataset (NED). Downloaded in 2010. See https://gdg.sc.egov.usda.gov/Catalog/ProductDescription/NED.html for more information.",
            "shortDescription": "30 meter USGS digital elevation model",
            "uri": "http://bagis.geog.pdx.edu/arcgis/services/BAGIS_GISLayers/DEM_westus_bc_30m/ImageServer",
            "layerType": "DEM",
            "heading": "Digital Elevation Model (DEM)"
        },

**Entries with short descriptions:**
        {
            "units": "Millimeters",
            "description": "SWE Data Source - Averaged daily SNOw Data Assimilation System (SNODAS) Snow Water Equivalent (SWE) from 2004 to current water year data. See https://www.nohrsc.noaa.gov/ for more information.",
            "shortDescription": "2004-2020 SNODAS daily data",
            "uri": "http://bagis.geog.pdx.edu/arcgis/services/DAILY_SWE_NORMALS/",
            "layerType": "Snotel SWE",
            "heading": "Snow Water Equivalent (SWE)"
        },
        {
            "units": "Inches",
            "description": "30-year (1991-2020) monthly/quarterly/annual average precipitation data created by the PRISM Climate Group. See https://prism.oregonstate.edu/ for more information.",
            "shortDescription": "PRISM 1991-2020 precipitation averages",
            "uri": "http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1991_2020/",
            "layerType": "Precipitation",
            "heading": "Precipitation"
        },
        {
            "description": "2019 NLCD Land Cover. See https://www.mrlc.gov for more information.",
            "shortDescription": "2019 National Land Cover Database (NLCD)",
            "uri": "http://bagis.geog.pdx.edu/arcgis/rest/services/BAGIS_Databin/NLCD_2019_land_cover/ImageServer",
            "layerType": "Land Cover",
            "heading": "Land Cover – for Potential Site Location Analysis"
        },



This is related to the data sources page and the "shortDescription" information

**Comment by jdduh** [comment] 2022-11-21 23:23
See the pdf for specific edits.

[Pages1&2 of 06099500_MT_USGS_Watershed-Report_Updates.pdf](https://github.com/PSU-CSAR/bagis-pro/files/10061286/Pages1.2.of.06099500_MT_USGS_Watershed-Report_Updates.pdf)

**Comment by lbross** [comment] 2022-11-21 23:55
Do you want to add the short descriptions to the data sources page? I am concerned that adding the DEM data source along with (potentially) the 2 new sites data sources is going to push this onto 2 pages.

**Comment by jdduh** [comment] 2022-11-21 23:58
No need to include shortDescription in the data sources. Please keep the summary page and the data sources page on one page each. I will provide the edits on other pages that use the shortDescriptions.

**Comment by lbross** [comment] 2022-11-23 19:25
Is it okay to have the short description apply only going forward? I ask because the data source information is copied to an .xml file in the AOI when the layers are clipped. I pull the information for the Data Sources page from this local file. Any layers clipped prior to this enhancement won't have the short description in their xml. There are things I could do to get the information from the server retroactively, but it is extra processing if its not necessary.

**Comment by jdduh** [comment] 2022-11-23 20:48
That would be OK to not have the shortDescription in previously process AOIs. We don't have an official release of the tool yet.

**Comment by lbross** [comment] 2022-11-28 19:52
Please review the title and data sources page for the D:\AOIs\2020_NWCC_Basin_Analysis_AOIs\Snake_River\HUC1706\Imnaha_R_at_Imnaha_11272010\13292000_OR_USGS_Watershed-Report.pdf on CS3 to ensure that I picked up all of your edits.
For the short description, do you want to provide a matrix of which maps get which short description by map title? Or would you like me to create the matrix and you can review? For example, the DEM description would obviously be on the Elevation Distribution map, but it could also be on the Forested Land Cover map since that is the base map that we use. Although Forested Land Cover is derived from the NLCD layer which has its own short description.

**Comment by jdduh** [comment] 2022-11-28 20:10
I am tempted to create 3 shortDescriptions for the PRISM precip data for monthly/quarterly/annual respectively. Let me know if there is any concern. I will confirm with my final edits on the report.

{
"units": "Inches",
"description": "30-year (1991-2020) monthly/quarterly/annual average precipitation data created by the PRISM Climate Group. See https://prism.oregonstate.edu/ for more information.",
"shortDescription": "PRISM 1991-2020 precipitation averages",
"uri": "http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1991_2020/",
"layerType": "Precipitation",
"heading": "Precipitation"
},

**Comment by lbross** [comment] 2022-11-28 23:49
Unfortunately I can't think of an efficient way to support 3 separate short descriptions for the PRISM precip data with the currently planned infrastructure. The short description is saved to the AOI analysis.xml file as part of the data source entry when the Prism layers are clipped and we only have a single entry for all the layers.

We could add the alternative short descriptions to the configuration file on the server and read it from there, but that will update as the years on the precipitation data are rolled forward, so it will probably get out of sync with what was actually clipped.

One thing that might work is to add the starting and ending prism years to the analysis.xml as separate data fields. Then I can compose the short description string on the fly, plugging in the years, for the other maps. Not as straightforward as the original design, but doable.

**Comment by jdduh** [comment] 2022-11-29 00:22
Can we add anther attribute to the PRISM and call it, shortDescriptionMonthly? We can reserve the shortDescription for annual precipitation.
Something like this:

{
"units": "Inches",
"description": "30-year (1991-2020) monthly/quarterly/annual average precipitation data created by the PRISM Climate Group. See https://prism.oregonstate.edu/ for more information.",
"shortDescription": "PRISM 1991-2020 **annual** precipitation averages",
**"shortDescriptionMonthly": "PRISM 1991-2020 monthly precipitation averages",**
"uri": "http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1991_2020/",
"layerType": "Precipitation",
"heading": "Precipitation"
},

**Comment by lbross** [comment] 2022-11-29 22:41
We can try your suggestion. I'm not 100% sure how it will work to have a property that only exists in one record. I am using dynamic data structures. But we can try it. I am going to change the name to make it more generic though in case we need to do something similar with another data source down the road. Perhaps shortDescription2?

**Comment by jdduh** [comment] 2022-11-29 22:42
Sounds good.

**Comment by jdduh** [comment] 2022-12-14 18:23
Add total site # at the beginning of the the individual snow monitoring site summary. See example on the image.

![image](https://user-images.githubusercontent.com/11510708/207677109-548c0eca-65d9-47a7-b7ae-97239692c13e.png)

**Comment by jdduh** [comment] 2022-12-16 02:35
We have a new PRISM dataset. Please update the description (by adding ", Version M4, released in December 2022" behind 1991-2020. The new dataset overrides the existing 1991-2020 imageservices on the server.

{
"units": "Inches",
"description": "30-year (1991-2020, Version M4, released in December 2022) monthly/quarterly/annual average precipitation data created by the PRISM Climate Group. See https://prism.oregonstate.edu/ for more information.",
"shortDescription": "PRISM 1991-2020 annual precipitation averages",
"shortDescriptionMonthly": "PRISM 1991-2020 monthly precipitation averages",
"uri": "http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1991_2020/",
"layerType": "Precipitation",
"heading": "Precipitation"
},

**Comment by lbross** [comment] 2022-12-16 18:35
Both of 2 preceding items are done. Note that the updated description will only be reflected in PRISM layers clipped from here forward. Also, I decided not to implement the "shortDescriptionMonthly" parameter. I use some string replacement in the application to replace annual with monthly where appropriate.

Finally ... I noticed in the desktop_settings.yaml file that the entry for BAGIS V3 in that file is still pointed to http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1981_2010. Do we want to update that to http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1991_2020/?

**Comment by jdduh** [comment] 2022-12-16 19:05
Sounds good with the plan to keep just the shortDescription. Yes, please set the default PRISM of BAGIS V3 to the 1991_2020 version.

**Comment by jdduh** [comment] 2022-12-30 22:44
Updated description for the public land ownership layer. The information is updated on the server definition file.

{
            "description": "Federal non-wilderness and tribal land data based on the 2020 USGS Protected Areas Data (PAD) version 2.1 **and the 2010 USA Indian Reservations dataset.** See https://www.usgs.gov/programs/gap-analysis-project/science/pad-us-data-overview **and https://www.sciencebase.gov/catalog/item/4f4e4a2ee4b07f02db61576c** for more information.",
            "uri": "https://services.arcgis.com/SXbDpmb7xQkk44JV/arcgis/rest/services/Public_and_Tribal_Lands/FeatureServer/0",
            "layerType": "Land Ownership",
            "heading": "Public Land Ownership – for Potential Site Location Analysis"
        },

**Comment by lbross** [comment] 2023-01-03 19:11
Thanks for letting me know. I have updated the desktop_settings.yaml in GitHub and confirmed that the new description appears properly on the data sources page for an AOI where the ownership layer was clipped today.

**Comment by jdduh** [comment] 2023-01-03 19:14
Thanks! Please update the desktop_settings.yaml for BAGIS V3 so that the PRISM source points to http://bagis.geog.pdx.edu/arcgis/services/BAGIS_PRISM_1991_2020/.

**Comment by lbross** [comment] 2023-01-03 19:17
I did this a couple of weeks ago but you won't see it in BAGIS v3 unless you update to the default settings. I think there is a button for this.

**Comment by jdduh** [comment] 2023-01-03 19:25
Thanks for updating the PRISM data source. I have been using BAGIS V3 without having PRISM data clipped to the AOIs. The clipping will happen in the BAGIS Pro batch tool. We will need to update the data sources when running the batch tool on Alaskan AOIs (see #40).

**Comment by jdduh** [comment] 2024-03-03 20:26
New data source metadata for fire layers. See #49 and #50.

{
"description": "National Interagency Fire Center (NIFC) historic wildland fires webservices accessed on the report creating date (see the report summary page). See https://data-nifc.opendata.arcgis.com/datasets/nifc::interagencyfireperimeterhistory-all-years-view/about for more information.",
"uri": "https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/InterAgencyFirePerimeterHistory_All_Years_View/FeatureServer/0",
"layerType": "Wildland Fires - Historic",
"heading": "NIFC Wildland Fires"
},
{
"description": "National Interagency Fire Center (NIFC) current wildland fires webservices accessed on the report creating date (see the report summary page). See https://data-nifc.opendata.arcgis.com/datasets/nifc::wfigs-interagency-fire-perimeters/about for more information.",
"uri": "https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/WFIGS_Interagency_Perimeters/FeatureServer/0",
"layerType": "Wildland Fires - Current",
"heading": "NIFC Wildland Fires"
},

The information for MTBS needs further verification depending on the use of USDA WMS or PSU ArcGIS Imageservice.

{
"description": "Monitoring Trends in Burn Severity (MTBS) burn severity and extent of large fires webservices accessed on the report creating date (see the report summary page). See https://mtbs.gov/project-overview for more information.",
"uri": "https://apps.fs.usda.gov/arcx/rest/services/RDW_Wildfire/MTBS_CONUS/MapServer/WMSServer/",
"layerType": "Wildland Fires - Burn Severity",
"heading": "MTBS Fire Burn Severity"
},

**Comment by jdduh** [comment] 2024-03-03 20:29
We will need a separate summary page for the fire reports. Please don't include the original Basin Report data sources that are not used in the fire reports for now. We might need to have a merged document in future projects.

**Comment by lbross** [comment] 2024-03-04 19:12
I just checked the algorithm that generates the Basin Report data sources on the title page. We provide a list of the data sources that can appear on this page (if used). If the fire data sources aren't on this list (and they currently are not), they won't be on the title page. I'm going to close this issue again. We can create a new issue if we need to modify the main title page for the fire data.

**Closed by lbross** 2024-03-04 19:12 UTC
